TOOLKIT=C:\Program Files (x86)\Civ4SDK\Microsoft Visual C++ Toolkit 2003
PSDK=C:\Program Files (x86)\Civ4SDK\WindowsSDK
CIV4_PATH=C:\Users\russel.BACKFENCE\AppData\Roaming\Firaxis Games\Sid Meier's Civilization 4\Beyond the Sword\
